### ISSUE TITLE
Whole loader is not centered

### ISSUE THREAD

**Issue by femto-code** [emanuele-scarsella/vortex-ubuntu-plymouth-theme#1]
The spinner as well as the progressbar don't seem to appear centered. Instead they appear in top left...

**Comment by emanuele-scarsella** [comment]
Plase, give some more details abount your setup:
Which version and distro are you using?
How many displays do you have connected?

**Comment by femto-code** [comment]
Ah, sorry.
Distro: KDE Neon 5.23 (latest)
One additional monitor connected

**Comment by emanuele-scarsella** [comment]
this theme has been designed and tested just for Ubuntu 20.04 LTS.
It might be due to the different distro but this theme is known to not center properly when more then one monitor is connected.
Try disconnecting the second monitor and check if it is then centered, if so it means that's because this theme doesn't take into account more then one monitor... i might try to fix it later in the month but at the moment I'm busy with my job so it may take some time.
Let me know if it works with just one monitor and I'm sorry for the bug you found

**Comment by femto-code** [comment]
I think this does not happen because of the different distro. KDE neon btw is basically Ubuntu 20.04 LTS.
But you are right, when I disconnect the second monitor, the loader is centered!
